# Form implementation generated from reading ui file 'ExitWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Quit(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(406, 137)
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(80, 90, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Proxima Nova")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 90, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(60, 20, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Proxima Nova")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Выход"))
        self.pushButton.setText(_translate("Dialog", "Отмена"))
        self.pushButton_2.setText(_translate("Dialog", "Выйти"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Вы уверены, что хотите выйти?</p><p align=\"center\">Все внесенные изменения будут потеряны</p></body></html>"))
