# Form implementation generated from reading ui file 'WelcomeWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(525, 353)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 270, 141, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 511, 101))
        font = QtGui.QFont()
        font.setFamily("Proxima Nova")
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(220, 130, 101, 101))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/Users/liparitgegaman/Desktop/lupa&pupa/Lip2C/ProgrammeFiles/Gerb_shkoly.png"))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Помоги Психологу"))
        self.pushButton.setText(_translate("Dialog", "Далее"))
        self.pushButton.setShortcut(_translate("Dialog", "Return"))
        self.pushButton_2.setText(_translate("Dialog", "Выход"))
        self.pushButton_2.setShortcut(_translate("Dialog", "Esc"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Добро пожаловать в мастер обработки документов<br/>для педагогов-психологов!<br/><br/></span><span style=\" font-size:14pt; font-style:italic;\">Сбросим с себя оковы! Долой труд дешевый!</span></p></body></html>"))
